name: Test
run-name: "[Test] ${{ github.event.head_commit.message }}"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    strategy:
      matrix:
        environment: [dev, uat, prod, test]
    environment: ${{matrix.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Environment on Build
        run: echo "${{matrix.environment}}"

  deploy:
    strategy:
      matrix:
        environment: [dev, uat, prod, test]
    environment: approve-${{matrix.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Environment on deploy
        run: echo "${{matrix.environment}}"
