name: Test
run-name: "[Test] ${{ github.event.head_commit.message }}"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Environment on Build
        run: echo "${{matrix.environment}}"

  approve:
    needs: build
    strategy:
      matrix:
        environment: [dev, uat, prod]
    environment: approve-${{matrix.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Environment on Approve
        run: echo "${{matrix.environment}}"

  deploy:
    needs: approve
    strategy:
      matrix:
        environment: [dev, uat, prod]
    environment: deploy-${{matrix.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Environment on Deploy
        run: echo "${{matrix.environment}}"
