name: PR Validation

on:
  pull_request:
    branches:
      - develop
      - master

permissions:
  id-token: write
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ValidatePullRequest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
